[package]
name = "rusty_jsc"
version = "0.0.1"
description = "Rust bindings for the JavaScriptCore engine"
authors = [ "Pekka Enberg" ]
license = "MIT"
repository = "https://github.com/penberg/rusty_jsc"
edition = "2021"

[lib]

[dependencies]
rusty_jsc_sys = { path = "./sys" }
