[package]
name = "rusty_jsc_sys"
version = "0.0.2"
description = "Raw bindings for the JavaScriptCore engine"
authors = [ "Pekka Enberg" ]
license = "MIT"
edition = "2021"

[lib]

[target.'cfg(target_os = "linux")'.build-dependencies]
pkg-config = "0.3.9"
